services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: portomoran:local
    ports:
      - "8080:80"
    volumes:
      - ./src:/usr/share/nginx/html:ro

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: portomoran-api:local
    ports:
      - "4000:4000"
    volumes:
      - ./api/src:/app/src:ro
    environment:
      - NODE_ENV=development

  db:
    ports:
      - "5432:5432"   # Akses langsung ke DB dari lokal

  redis:
    ports:
      - "6379:6379"   # Akses langsung ke Redis dari lokal

  prometheus:
    ports:
      - "9090:9090"   # http://localhost:9090

  grafana:
    ports:
      - "3000:3000"   # http://localhost:3000

  alertmanager:
    ports:
      - "9093:9093"   # http://localhost:9093

  # Nonaktifkan cloudflared di lokal
  cloudflared:
    profiles:
      - production
